apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: stysk6rvs-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-a88c4665a2.ps9p.p3.openshiftapps.com/rhtap/rhtap-qe:6a1fe7721564974213e529cbe0b764336782e573@sha256:857d9fd597cd79326f4d03431499a81a6a8a9bd6daf28c2098b1c34832f2c402
          name: container-image
